<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>fs_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="fs_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FS2Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FS2Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FS2Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FS2Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>