<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>fs_icon.ico</ApplicationIcon>
	<DebugType>none</DebugType>
	<Optimize>true</Optimize>
	<Version>2.0.4.1</Version>
	<AssemblyVersion>2.0.4.1</AssemblyVersion>
	<FileVersion>2.0.4.1</FileVersion>
	<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fs2_help.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="fs_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="fs2_help.txt" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FS2Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FS2Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="SVGres.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SVGres.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="FS2Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>FS2Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SVGres.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SVGres.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg" Version="3.3.0" />
  </ItemGroup>

</Project>